language: php

cache:
   directories:
     - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3

sudo: true

matrix:
  include:
    - php: 7.1
      env: LARAVEL_VERSION=5.1.*

    - php: 7.1
      env: LARAVEL_VERSION=5.3.*

    - php: 7.1
      env: LARAVEL_VERSION=5.5.*

    - php: 7.1
      env: LARAVEL_VERSION=5.6.*

    - php: 7.1
      env: LARAVEL_VERSION=5.7.*
    - php: 7.2
      env: LARAVEL_VERSION=5.7.*
    - php: 7.3
      env: LARAVEL_VERSION=5.7.*

    - php: 7.2
      env: LARAVEL_VERSION=5.8.*
    - php: 7.3
      env: LARAVEL_VERSION=5.8.*

    - php: 7.2
      env: LARAVEL_VERSION=6.0.*
    - php: 7.3
      env: LARAVEL_VERSION=6.0.*

    - php: 7.2
      env: LARAVEL_VERSION=6.1.*
    - php: 7.3
      env: LARAVEL_VERSION=6.1.*

    - php: 7.2
      env: LARAVEL_VERSION=6.2.*
    - php: 7.3
      env: LARAVEL_VERSION=6.2.*

    - php: 7.2
      env: LARAVEL_VERSION=6.3.*
    - php: 7.3
      env: LARAVEL_VERSION=6.3.*

    - php: 7.2
      env: LARAVEL_VERSION=6.4.*
    - php: 7.3
      env: LARAVEL_VERSION=6.4.*

    - php: 7.2
      env: LARAVEL_VERSION=6.5.*
    - php: 7.3
      env: LARAVEL_VERSION=6.5.*

before_install:
  - composer self-update --stable -n

install:
  - travis_retry composer install --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover clover.xml;

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar;
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml;
  - bash <(curl -s https://codecov.io/bash)